-- Database: linda

-- DROP DATABASE linda;

CREATE DATABASE linda
  WITH OWNER = postgres
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       LC_COLLATE = 'en_US.utf8'
       LC_CTYPE = 'en_US.utf8'
       CONNECTION LIMIT = -1;


CREATE ROLE estatistica LOGIN
  ENCRYPTED PASSWORD 'md5f82024a95405f2ee8f854be66cd4d939'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;

CREATE ROLE icareweb LOGIN
  ENCRYPTED PASSWORD 'md5f82024a95405f2ee8f854be66cd4d939'
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;
